# ビルドに使うworkspace/stack.yamlのGHCのバージョンが古くHLSに対応していません。
# そのため、VSCodeのHaskell拡張機能を有効にするため、このstack.yamlを読み込ませます。
# 実際はworkspaceでビルドします。

# This is stack.yaml for loading HLS
# This is not true stack.yaml
# Please build by ''./workspace/stack.yaml'

resolver: lts-18.28

packages:
  - ./hello-seed

extra-deps: 
  - ease-0.1.0.2@sha256:03f620cd1f2347823d46168419c39a570ed555b67edd48294d07ebe723c02388,899

flags: {}

extra-package-dbs: []
