language: haskell

sudo: required

env:
  - GHCVER=8.0.2 CABALVER=1.24 HAPPYVER=1.19.5 LD_LIBRARY_PATH=/usr/local/lib

before_install:
  - cd ..

  # Install SDL.
  - wget -q http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar xf SDL2-*.tar.gz
  - cd SDL2-* && ./configure && make && sudo make install && cd ..

  # Install SDL_gfx.
  - wget -q http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.1.tar.gz
  - tar xf SDL2_gfx-*.tar.gz
  - cd SDL2_gfx-* && ./autogen.sh && ./configure && make && sudo make install && cd ..

  # Install ghc, cabal-install and happy.
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-$HAPPYVER
  - export CABAL=/opt/cabal/bin/cabal-$CABALVER
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - rm -rf ~/.cabal
  - $CABAL update
  - $CABAL --version

install:
  # Install haskell-game/sdl2.
  - git clone https://github.com/haskell-game/sdl2.git
  - cd sdl2 && $CABAL install --flags="no-linear" && cd ..

script:
  - cd sdl2-gfx
  - $CABAL install --flags="example"
